spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
